### ISSUE TITLE
Add google analytics to gitconnected

### ISSUE THREAD

**Issue by mblodorn** [gitconnected/gitconnected#2]
Hey,

I was wandering between gitconnected files and noticed that google analytics is not imported in the html file. Not sure if it's somewhere else or not present at all, but Google Analytics is easy to setup and provides a lot of useful information that can help gitconnected to grow.

**Comment by treyhuffine** [comment]
Thanks for looking into that! We're actually injecting Google Analytics via Google Tag Manager.

**Comment by mblodorn** [comment]
Great! I guess that we can close the first issue then. 🥇 

Thanks for the fast reply!
