### ISSUE TITLE
Voting on Tutorials and courses

### ISSUE THREAD

**Issue by Trewaters** [gitconnected/gitconnected#8]
I was looking through the list of tutorials and courses when I thought of this. 

Personally I refrain from "liking" or voting on articles until I have vetted them, to some degree. In this case I clicked on a tutorial from "Home / Coding Tutorials / React" (https://gitconnected.com/learn/react). When I did that a new window opened, which is great. After I was done with the article I wanted to "vote it up" but realized that it would be difficult to find the article if I had closed the original window.

**My thought is offering users a way to** ...
- view 
or
- easily find/review

...the last article they opened. Maybe even a user history of what was visited so they can later review and upvote it.

This is only a brainstorm idea, but I think some way to easily find and vote on an article you have found from the gitconnected site would be nice.

**Comment by treyhuffine** [comment]
Or maybe a way to bookmark it.  What do you think would be better @Trewaters - remembering all recent tutorials permanently or remembering recent tutorials in the current browser session and allowing users to bookmark the ones they like for longterm access?

**Comment by treyhuffine** [comment]
Got it, makes total sense. So do you think the current implementation covers the pain points you were having?

**Comment by Trewaters** [comment]
I think you nailed it!

Not obtrusive or jarring. Just enough of a reminder for someone like me that is trying to test the article before I actually up vote it.

I like how there are words communicating to the user. Plus you added a highlight, in a different color to bring my eye to the change. Bravo!

**Comment by treyhuffine** [comment]
Awesome! 😄 I'm going to mark this issue as closed. Let me know if you have any other suggestions.
